import type {
  TimelineDataset,
  TimelineItem,
  TimelineLocation,
  TimelineTrack,
} from "@/domain/timeline/types";

export const DEMO_TRACKS: TimelineTrack[] = [
  {
    id: "track-korea",
    key: "korean-history",
    name: "한국사",
    parentKey: null,
    order: 1,
    color: "#0f766e",
    visible: true,
    description: "한반도의 정치, 사회, 문화사",
  },
  {
    id: "track-world",
    key: "world-history",
    name: "세계사",
    parentKey: null,
    order: 2,
    color: "#2563eb",
    visible: true,
    description: "국제 질서, 혁명과 문명의 변화",
  },
  {
    id: "track-christian",
    key: "christian-history",
    name: "기독교사",
    parentKey: null,
    order: 3,
    color: "#b45309",
    visible: true,
    description: "교회, 교리, 운동과 선교의 역사",
  },
  {
    id: "track-conservative",
    key: "conservative-history",
    name: "보수주의사",
    parentKey: null,
    order: 4,
    color: "#b91c1c",
    visible: true,
    description: "보수 사상, 저작과 정치 운동",
  },
  {
    id: "track-ai",
    key: "ai-history",
    name: "AI사",
    parentKey: null,
    order: 5,
    color: "#6d28d9",
    visible: true,
    description: "계산 이론, 인공지능 연구와 산업",
  },
];

export const DEMO_ITEMS: TimelineItem[] = [
  item({
    id: "reformation-1517",
    title: "종교개혁의 전개",
    type: "event",
    start: 1517,
    end: 1648,
    basis: "duration",
    tracks: ["christian-history", "world-history"],
    importance: "core",
    summary: "서방 기독교 세계와 유럽 정치 질서를 재편한 종교·사회적 변동",
    detail: "루터의 문제 제기에서 시작해 여러 교파의 형성과 종교전쟁, 베스트팔렌 질서로 이어진 장기 변화다.",
  }),
  item({
    id: "imjin-war-1592",
    title: "임진왜란",
    type: "event",
    start: 1592,
    end: 1598,
    basis: "duration",
    tracks: ["korean-history", "world-history"],
    importance: "core",
    summary: "일본의 조선 침략과 명의 참전으로 전개된 동아시아 국제전",
  }),
  item({
    id: "two-treatises-1689",
    title: "『통치론』 출간",
    type: "book",
    start: 1689,
    basis: "publication",
    tracks: ["world-history", "conservative-history"],
    importance: "major",
    summary: "로크가 정부의 정당성과 저항권을 논증한 정치철학 저작",
  }),
  item({
    id: "american-revolution-1775",
    title: "미국 독립혁명",
    type: "event",
    start: 1775,
    end: 1783,
    basis: "duration",
    tracks: ["world-history", "conservative-history"],
    importance: "core",
    summary: "식민지 독립과 공화정 수립을 통해 근대 정치 질서에 영향을 준 혁명",
  }),
  item({
    id: "reflections-1790",
    title: "『프랑스 혁명에 관한 성찰』",
    type: "book",
    start: 1790,
    basis: "publication",
    tracks: ["conservative-history", "world-history"],
    importance: "core",
    summary: "에드먼드 버크가 혁명과 정치적 변화의 원리를 비판적으로 논한 저작",
  }),
  item({
    id: "donghak-1894",
    title: "동학농민운동",
    type: "event",
    start: 1894,
    basis: "duration",
    tracks: ["korean-history", "world-history"],
    importance: "core",
    summary: "조선 후기의 사회 개혁 요구와 동아시아 국제 질서가 교차한 대규모 운동",
  }),
  item({
    id: "march-first-1919",
    title: "3·1 운동",
    type: "event",
    start: 1919,
    basis: "point",
    tracks: ["korean-history", "world-history", "christian-history"],
    importance: "core",
    summary: "일제강점기 전국적으로 전개된 독립 선언과 비폭력 저항 운동",
  }),
  item({
    id: "korean-war-1950",
    title: "한국전쟁",
    type: "event",
    start: 1950,
    end: 1953,
    basis: "duration",
    tracks: ["korean-history", "world-history"],
    importance: "core",
    summary: "한반도 분단과 냉전 질서를 고착시킨 국제전",
  }),
  item({
    id: "turing-test-1950",
    title: "「Computing Machinery and Intelligence」",
    type: "book",
    start: 1950,
    basis: "publication",
    tracks: ["ai-history"],
    importance: "core",
    summary: "앨런 튜링이 기계 지능을 논하고 모방 게임을 제시한 논문",
  }),
  item({
    id: "dartmouth-1956",
    title: "다트머스 회의",
    type: "event",
    start: 1956,
    basis: "point",
    tracks: ["ai-history"],
    importance: "core",
    summary: "인공지능이라는 연구 분야의 명칭과 의제를 조직한 여름 연구 프로젝트",
    location: {
      name: "미국 뉴햄프셔주 하노버",
      latitude: 43.7044,
      longitude: -72.2887,
      precision: "approximate",
    },
  }),
  item({
    id: "vatican-two-1962",
    title: "제2차 바티칸 공의회",
    type: "event",
    start: 1962,
    end: 1965,
    basis: "duration",
    tracks: ["christian-history", "world-history"],
    importance: "core",
    summary: "가톨릭교회의 전례, 교회론과 현대 세계와의 관계에 큰 변화를 준 공의회",
  }),
  item({
    id: "democratization-1987",
    title: "6월 민주항쟁",
    type: "event",
    start: 1987,
    basis: "point",
    tracks: ["korean-history", "world-history"],
    importance: "core",
    summary: "대통령 직선제 개헌과 민주화 이행을 이끈 전국적 시민 항쟁",
  }),
  item({
    id: "deep-blue-1997",
    title: "딥 블루의 체스 승리",
    type: "technology",
    start: 1997,
    basis: "point",
    tracks: ["ai-history", "world-history"],
    importance: "major",
    summary: "IBM 딥 블루가 세계 체스 챔피언과의 매치에서 승리한 사건",
  }),
  item({
    id: "alexnet-2012",
    title: "AlexNet",
    type: "technology",
    start: 2012,
    basis: "point",
    tracks: ["ai-history"],
    importance: "core",
    summary: "대규모 이미지 인식에서 심층 신경망의 성능을 널리 입증한 모델",
  }),
  item({
    id: "transformer-2017",
    title: "Transformer 발표",
    type: "technology",
    start: 2017,
    basis: "point",
    tracks: ["ai-history"],
    importance: "core",
    summary: "어텐션 중심 구조로 현대 생성형 AI의 기반이 된 신경망 아키텍처",
  }),
  item({
    id: "chatgpt-2022",
    title: "ChatGPT 공개",
    type: "technology",
    start: 2022,
    basis: "point",
    tracks: ["ai-history", "world-history"],
    importance: "core",
    summary: "대화형 생성 AI가 대중적으로 확산되는 계기가 된 서비스 공개",
  }),
];

export const DEMO_DATASET: TimelineDataset = {
  source: "demo",
  tracks: DEMO_TRACKS,
  items: DEMO_ITEMS,
};

function item(input: {
  id: string;
  title: string;
  type: TimelineItem["type"];
  start: number;
  end?: number;
  basis: TimelineItem["time"]["basis"];
  tracks: string[];
  importance: TimelineItem["importance"];
  summary: string;
  detail?: string;
  location?: TimelineLocation;
}): TimelineItem {
  return {
    id: input.id,
    slug: input.id,
    visibility: "published",
    bookmarked: false,
    title: input.title,
    type: input.type,
    time: {
      start: { year: input.start, era: "CE", precision: "year" },
      end: input.end
        ? { year: input.end, era: "CE", precision: "year" }
        : null,
      basis: input.basis,
    },
    trackKeys: input.tracks,
    tags: [],
    importance: input.importance,
    summary: input.summary,
    detail: input.detail ?? input.summary,
    recordLevel: "simple",
    confidence: "high",
    locations: input.location ? [input.location] : [],
    sources: [],
  };
}
