import type { ImportItem } from "../domain/import/schema";

type DateSpec = {
  year: number;
  era?: "BCE" | "CE";
  precision?: ImportItem["time"]["start"]["precision"];
};

type SeedItem = {
  title: string;
  type?: ImportItem["type"];
  start: DateSpec;
  end?: DateSpec;
  basis?: ImportItem["time"]["basis"];
  tracks: string[];
  tags: string[];
  importance?: ImportItem["importance"];
  summary: string;
  detail: string;
  confidence?: ImportItem["confidence"];
  uncertaintyNote?: string;
  location?: ImportItem["location"];
  sources: ImportItem["sources"];
};

const US_TIMELINE = source(
  "reference",
  "U.S. History Primary Source Timeline",
  "Library of Congress",
  "https://www.loc.gov/classroom-materials/united-states-history-primary-source-timeline/",
);
const US_FOUNDING = source(
  "primary",
  "America's Founding Documents",
  "U.S. National Archives",
  "https://www.archives.gov/founding-docs",
);
const CHINA_TIMELINE = source(
  "reference",
  "China - Timeline of Historical Periods",
  "Columbia University, Asia for Educators",
  "https://afe.easia.columbia.edu/timelines/china_timeline.htm",
);
const ESV_BIBLE = source(
  "reference",
  "Overview of the Bible",
  "ESV Global Study Bible",
  "https://www.esv.org/resources/esv-global-study-bible/overview-of-the-bible/",
);
const ESV_EXODUS = source(
  "reference",
  "Introduction to Exodus",
  "ESV Global Study Bible",
  "https://www.esv.org/resources/esv-global-study-bible/introduction-to-exodus/",
);
const ESV_NEW_TESTAMENT = source(
  "reference",
  "New Testament: Theology and Key Dates",
  "ESV Global Study Bible",
  "https://www.esv.org/resources/esv-global-study-bible/new-testament-theology-and-key-dates/",
);
const ESV_ACTS = source(
  "reference",
  "Introduction to Acts",
  "ESV Global Study Bible",
  "https://www.esv.org/resources/esv-global-study-bible/introduction-to-acts/",
);
const ROME_REPUBLIC = source(
  "reference",
  "The Roman Republic",
  "The Metropolitan Museum of Art",
  "https://www.metmuseum.org/essays/the-roman-republic",
);
const ROME_EMPIRE = source(
  "reference",
  "The Roman Empire (27 B.C.-393 A.D.)",
  "The Metropolitan Museum of Art",
  "https://www.metmuseum.org/essays/the-roman-empire-27-b-c-393-a-d",
);

export const CORE_HISTORY_TRACKS = [
  {
    key: "american-history",
    name: "미국사",
    order: 5,
    color: "red",
    visible: true,
    description: "식민지 시대부터 건국, 내전, 개혁과 현대 미국의 변화를 추적합니다.",
  },
  {
    key: "chinese-history",
    name: "중국사",
    order: 6,
    color: "amber",
    visible: true,
    description: "고대 왕조부터 제국 질서와 근현대 중국의 변화를 추적합니다.",
  },
  {
    key: "israel-history",
    name: "이스라엘사",
    order: 7,
    color: "green",
    visible: true,
    description: "복음주의 개신교의 성경 서사를 중심으로 고대 이스라엘과 예수 시대, 현대 이스라엘을 함께 봅니다.",
  },
  {
    key: "philosophy-history",
    name: "철학사",
    order: 8,
    color: "violet",
    visible: true,
    description: "동서양의 핵심 철학자와 저작, 사상의 전환을 추적합니다.",
  },
  {
    key: "science-history",
    name: "과학사",
    order: 9,
    color: "gray",
    visible: true,
    description: "과학적 세계관을 바꾼 이론, 관측, 실험과 기술을 추적합니다.",
  },
] as const;

export const CORE_HISTORY_ITEMS: ImportItem[] = [
  historyItem({
    title: "제임스타운 정착촌 설립",
    start: { year: 1607 },
    tracks: ["american-history", "world-history"],
    tags: ["미국사", "식민지", "대서양 세계"],
    summary: "버지니아의 제임스타운이 잉글랜드 최초의 지속적 북아메리카 정착촌으로 세워졌다.",
    detail: "제임스타운은 북아메리카 영국 식민지의 지속적 확장을 위한 거점이 되었다. 원주민 사회와의 충돌, 담배 경제, 계약 노동과 노예제의 성장은 이후 미국사의 주요 구조를 형성했다.",
    location: location("제임스타운", 37.208, -76.775, "approximate"),
    sources: [US_TIMELINE],
  }),
  historyItem({
    title: "미국 독립선언 채택",
    start: { year: 1776 },
    type: "book",
    basis: "publication",
    tracks: ["american-history", "world-history", "philosophy-history"],
    tags: ["미국사", "독립선언", "자연권"],
    summary: "대륙회의가 독립선언을 채택해 13개 식민지의 독립과 자연권·인민주권의 원리를 천명했다.",
    detail: "1776년 7월 4일 채택된 독립선언은 영국과의 정치적 분리를 선언하고 생명, 자유, 행복 추구의 권리를 정부 정당성의 근거로 제시했다.",
    location: location("필라델피아 독립기념관", 39.9489, -75.15, "exact"),
    sources: [US_FOUNDING],
  }),
  historyItem({
    title: "미국 헌법 제정과 연방 체제 수립",
    start: { year: 1787 },
    type: "book",
    basis: "publication",
    tracks: ["american-history", "world-history", "philosophy-history"],
    tags: ["미국사", "헌법", "연방제", "권력분립"],
    summary: "필라델피아 헌법회의가 권력분립과 연방제를 골격으로 하는 미국 헌법에 서명했다.",
    detail: "1787년 헌법은 연합규약의 한계를 보완해 연방정부의 입법·행정·사법 구조를 만들었다. 이후 비준과 권리장전 채택을 거쳐 미국 헌정 질서의 기반이 되었다.",
    location: location("필라델피아 독립기념관", 39.9489, -75.15, "exact"),
    sources: [US_FOUNDING],
  }),
  historyItem({
    title: "미국 남북전쟁",
    start: { year: 1861 },
    end: { year: 1865 },
    tracks: ["american-history", "world-history"],
    tags: ["미국사", "남북전쟁", "노예제"],
    summary: "노예제와 연방의 성격을 둘러싼 갈등이 연방과 남부연합 사이의 내전으로 폭발했다.",
    detail: "남북전쟁은 연방의 존속과 노예제 폐지를 결정한 미국사의 최대 내전이었다. 전쟁의 결과 남부연합은 패배하고 수정헌법 제13조를 통해 노예제가 폐지되었다.",
    location: location("섬터 요새", 32.7523, -79.8747, "approximate"),
    sources: [US_TIMELINE],
  }),
  historyItem({
    title: "미국 재건 시대",
    start: { year: 1865 },
    end: { year: 1877 },
    tracks: ["american-history"],
    tags: ["미국사", "재건", "시민권"],
    summary: "내전 이후 남부의 연방 복귀와 해방민의 시민권을 둘러싼 정치·사회 재편이 진행됐다.",
    detail: "재건기에는 수정헌법 제13·14·15조가 채택되고 흑인 시민의 정치 참여가 확대되었다. 동시에 백인우월주의 폭력과 제도적 저항이 이어져 성과가 크게 후퇴했다.",
    sources: [US_TIMELINE],
  }),
  historyItem({
    title: "뉴딜 정책의 전개",
    start: { year: 1933 },
    end: { year: 1939, precision: "estimated" },
    tracks: ["american-history", "world-history"],
    tags: ["미국사", "대공황", "뉴딜"],
    summary: "루스벨트 행정부가 대공황에 대응해 금융 개혁, 공공사업, 사회보장 제도를 확대했다.",
    detail: "뉴딜은 연방정부가 경제 안정과 사회복지에 더 적극적으로 개입하는 전환점이었다. 단일 정책이 아니라 1930년대에 걸쳐 시행된 여러 구호·회복·개혁 프로그램의 묶음이다.",
    confidence: "medium",
    uncertaintyNote: "뉴딜의 종료 시점은 제2차 세계대전 동원과의 연속성을 어떻게 보느냐에 따라 달라진다.",
    location: location("워싱턴 D.C.", 38.9072, -77.0369, "approximate"),
    sources: [US_TIMELINE],
  }),
  historyItem({
    title: "미국 민권운동의 전개",
    start: { year: 1954 },
    end: { year: 1968 },
    tracks: ["american-history", "world-history"],
    tags: ["미국사", "민권운동", "인종차별 철폐"],
    summary: "법정 투쟁과 대중운동이 인종분리 제도와 흑인 참정권 제한에 맞서 연방법의 변화를 이끌었다.",
    detail: "브라운 판결, 몽고메리 버스 보이콧, 워싱턴 행진, 민권법과 투표권법은 민권운동의 핵심 이정표다. 운동은 법적 분리 철폐를 넘어 실질적 평등의 과제를 남겼다.",
    location: location("몽고메리", 32.3777, -86.3006, "approximate"),
    sources: [US_TIMELINE],
  }),

  historyItem({
    title: "상 왕조",
    start: { year: 1600, era: "BCE", precision: "estimated" },
    end: { year: 1050, era: "BCE", precision: "estimated" },
    tracks: ["chinese-history", "world-history"],
    tags: ["중국사", "상 왕조", "갑골문"],
    summary: "황허 유역의 상 왕조가 청동기 정치 질서와 갑골문 기록을 남겼다.",
    detail: "상 왕조는 문자 기록과 고고학 자료가 함께 확인되는 중국의 이른 왕조다. 안양의 은허와 갑골문은 왕권, 제사, 전쟁과 점복의 구조를 보여준다.",
    confidence: "medium",
    uncertaintyNote: "왕조의 시작 연도와 초기 중심지는 고고학 편년에 따라 다르게 제시된다.",
    sources: [CHINA_TIMELINE],
  }),
  historyItem({
    title: "주 왕조",
    start: { year: 1046, era: "BCE" },
    end: { year: 256, era: "BCE" },
    tracks: ["chinese-history", "world-history"],
    tags: ["중국사", "주 왕조", "천명", "춘추전국"],
    summary: "주 왕조가 천명 사상과 봉건적 질서를 전개했고 후기에 춘추전국의 경쟁 체제로 분화했다.",
    detail: "서주는 왕실과 제후의 관계를 통해 광범위한 정치 질서를 유지했다. 동주 시기에는 왕실 권위가 약화되고 춘추전국 시대의 국가 경쟁과 사상적 혁신이 이어졌다.",
    sources: [CHINA_TIMELINE],
  }),
  historyItem({
    title: "공자의 생애와 유가 사상의 형성",
    type: "person",
    start: { year: 551, era: "BCE" },
    end: { year: 479, era: "BCE" },
    basis: "lifespan",
    tracks: ["chinese-history", "philosophy-history"],
    tags: ["중국사", "철학사", "공자", "유가"],
    summary: "공자가 인·예·덕치와 배움의 실천을 가르쳐 동아시아 유가 전통의 토대를 놓았다.",
    detail: "공자의 가르침은 제자들이 전한 논어를 중심으로 계승되었다. 개인의 인격 수양, 관계 속의 책임, 예에 기초한 정치 질서는 이후 중국과 동아시아 사상에 지속적인 영향을 주었다.",
    confidence: "medium",
    uncertaintyNote: "전통적 생몰년은 널리 쓰이지만 공자의 생애 자료에는 후대 전승이 섞여 있다.",
    location: location("취푸", 35.5808, 116.9865, "approximate"),
    sources: [
      source(
        "reference",
        "Confucius",
        "Stanford Encyclopedia of Philosophy",
        "https://plato.stanford.edu/entries/confucius/",
      ),
    ],
  }),
  historyItem({
    title: "진의 중국 통일",
    start: { year: 221, era: "BCE" },
    end: { year: 206, era: "BCE" },
    tracks: ["chinese-history", "world-history"],
    tags: ["중국사", "진 왕조", "통일"],
    summary: "진시황이 전국시대를 끝내고 군현제, 문자와 도량형의 표준화를 추진했다.",
    detail: "진은 짧게 존속했지만 황제 칭호, 중앙집권적 군현제, 행정 표준화를 통해 이후 중국 제국의 기본 형식을 제시했다.",
    location: location("시안", 34.3416, 108.9398, "approximate"),
    sources: [CHINA_TIMELINE],
  }),
  historyItem({
    title: "한 왕조",
    start: { year: 206, era: "BCE" },
    end: { year: 220, era: "CE" },
    tracks: ["chinese-history", "world-history"],
    tags: ["중국사", "한 왕조", "실크로드"],
    summary: "한 왕조가 장기적 제국 통치와 유교적 관료 질서, 실크로드 교류를 발전시켰다.",
    detail: "전한과 후한은 진의 중앙집권 제도를 계승하면서 유교 경전을 국가 운영과 교육의 중요한 자원으로 삼았다. 서역과의 교류 확대는 유라시아 교역망을 촉진했다.",
    sources: [CHINA_TIMELINE],
  }),
  historyItem({
    title: "당 왕조",
    start: { year: 618 },
    end: { year: 907 },
    tracks: ["chinese-history", "world-history"],
    tags: ["중국사", "당 왕조", "장안"],
    summary: "당 왕조가 동아시아 국제질서와 개방적 도시문화, 광범위한 교역을 발전시켰다.",
    detail: "당은 장안을 중심으로 중앙집권 체제와 과거제를 발전시켰으며, 중앙아시아와 한반도·일본·동남아시아를 잇는 교류의 중심이 되었다.",
    sources: [CHINA_TIMELINE],
  }),
  historyItem({
    title: "송 왕조",
    start: { year: 960 },
    end: { year: 1279 },
    tracks: ["chinese-history", "world-history", "science-history"],
    tags: ["중국사", "송 왕조", "상업혁명", "과학기술"],
    summary: "송대에 상업·도시·인쇄·과학기술과 문치 관료제가 크게 발전했다.",
    detail: "북송과 남송은 군사적 압박 속에서도 시장경제, 해상무역, 인쇄문화와 기술 혁신을 심화했다. 성리학의 체계화도 이 시기의 중요한 지적 변화다.",
    sources: [CHINA_TIMELINE],
  }),
  historyItem({
    title: "원 왕조",
    start: { year: 1271 },
    end: { year: 1368 },
    tracks: ["chinese-history", "world-history"],
    tags: ["중국사", "원 왕조", "몽골 제국"],
    summary: "쿠빌라이가 원을 세우고 중국을 몽골 제국의 광대한 유라시아 네트워크와 연결했다.",
    detail: "원 왕조는 중국 전역을 지배한 몽골계 왕조로서 대도에 수도를 두었다. 육상·해상 교류가 확대되었지만 신분적 차등과 재정 문제도 심화됐다.",
    sources: [CHINA_TIMELINE],
  }),
  historyItem({
    title: "명 왕조",
    start: { year: 1368 },
    end: { year: 1644 },
    tracks: ["chinese-history", "world-history"],
    tags: ["중국사", "명 왕조", "정화 원정"],
    summary: "명 왕조가 한족 왕조를 복원하고 관료제, 대외 교역과 해금 정책을 교차적으로 운영했다.",
    detail: "명은 홍무제의 중앙집권 강화로 출발해 영락제 시기 베이징 천도와 정화 원정을 추진했다. 후기에는 은 경제와 세계 교역이 확대되는 한편 재정·군사 위기가 누적됐다.",
    sources: [CHINA_TIMELINE],
  }),
  historyItem({
    title: "청 왕조",
    start: { year: 1644 },
    end: { year: 1912 },
    tracks: ["chinese-history", "world-history"],
    tags: ["중국사", "청 왕조", "제국"],
    summary: "만주족의 청 왕조가 다민족 제국을 확장했으나 19세기 내외 위기 속에서 붕괴했다.",
    detail: "청은 광대한 영토와 다민족 통치 체제를 구축했다. 19세기에는 아편전쟁, 대규모 반란, 열강의 압력과 개혁 실패가 겹쳤고 1911년 혁명 뒤 왕조가 끝났다.",
    sources: [CHINA_TIMELINE],
  }),
  historyItem({
    title: "중화인민공화국 수립",
    start: { year: 1949 },
    tracks: ["chinese-history", "world-history"],
    tags: ["중국사", "중화인민공화국", "냉전"],
    summary: "중국공산당이 내전에서 승리하고 베이징에서 중화인민공화국 수립을 선포했다.",
    detail: "1949년의 정권 수립은 제국 붕괴 이후 이어진 혁명과 내전의 중대한 분기점이었다. 국민정부는 타이완으로 이동했고 양안의 정치적 분단이 고착됐다.",
    location: location("베이징 톈안먼", 39.9055, 116.3976, "approximate"),
    sources: [CHINA_TIMELINE],
  }),
  historyItem({
    title: "개혁개방의 시작과 확대",
    start: { year: 1978 },
    end: { year: 1992 },
    tracks: ["chinese-history", "world-history"],
    tags: ["중국사", "개혁개방", "시장화"],
    summary: "덩샤오핑 지도 아래 농업·기업·대외개방 개혁이 시작돼 중국 경제의 구조가 크게 바뀌었다.",
    detail: "1978년 이후 중국은 계획경제의 틀 안에 시장 기제를 단계적으로 도입하고 경제특구와 외국 투자를 확대했다. 1992년 남순강화는 개혁 노선을 재확인한 상징적 계기였다.",
    confidence: "medium",
    uncertaintyNote: "개혁개방은 현재까지 이어지는 장기 과정이며 여기서는 초기 제도화 단계를 1992년까지로 표시한다.",
    sources: [CHINA_TIMELINE],
  }),

  historyItem({
    title: "족장 시대: 아브라함에서 야곱까지",
    start: { year: 2166, era: "BCE", precision: "estimated" },
    end: { year: 1876, era: "BCE", precision: "estimated" },
    tracks: ["israel-history", "christian-history"],
    tags: ["이스라엘사", "성경사", "아브라함", "언약"],
    summary: "창세기의 아브라함·이삭·야곱 이야기가 이스라엘 언약 공동체의 기원을 이룬다.",
    detail: "복음주의 개신교의 성경 이해에서 하나님이 아브라함을 부르시고 언약을 세우신 사건은 이스라엘 역사와 구속사의 중요한 출발점이다. 연대는 전통적 성경 연대 계산을 따른다.",
    confidence: "disputed",
    uncertaintyNote: "족장 이야기의 절대연대는 성경 계보 계산과 고대 근동 자료 해석에 따라 크게 달라지며 독립적인 역사 검증이 제한적이다.",
    sources: [ESV_BIBLE],
  }),
  historyItem({
    title: "출애굽",
    start: { year: 1446, era: "BCE", precision: "estimated" },
    tracks: ["israel-history", "christian-history"],
    tags: ["이스라엘사", "성경사", "출애굽", "모세", "언약"],
    summary: "모세의 인도 아래 이스라엘이 이집트를 떠나고 시내산에서 언약 공동체로 세워졌다는 성경의 핵심 사건이다.",
    detail: "복음주의 개신교 전통에서 출애굽은 하나님의 구원과 언약을 보여주는 핵심 사건이며 신약의 그리스도 구원 이해에도 중요한 모형이 된다. 여기서는 열왕기상 6장 1절을 바탕으로 한 전통적 이른 연대인 기원전 1446년을 사용한다.",
    confidence: "disputed",
    uncertaintyNote: "개신교 학자들 사이에서도 기원전 1446년의 이른 연대와 기원전 13세기의 늦은 연대가 함께 제시되며, 사건의 고고학적 재구성에는 큰 논쟁이 있다.",
    sources: [ESV_EXODUS],
  }),
  historyItem({
    title: "가나안 정복과 정착",
    start: { year: 1406, era: "BCE", precision: "estimated" },
    end: { year: 1399, era: "BCE", precision: "estimated" },
    tracks: ["israel-history", "christian-history"],
    tags: ["이스라엘사", "성경사", "여호수아", "가나안"],
    summary: "여호수아가 이끄는 이스라엘이 요단을 건너 가나안에 정착했다는 성경 서사의 시기다.",
    detail: "복음주의 전통은 여호수아서를 출애굽 세대 다음 세대가 약속의 땅에 들어가는 언약 성취의 이야기로 읽는다. 정착은 단일 전쟁이 아니라 여러 지역과 세대에 걸친 과정으로도 이해된다.",
    confidence: "disputed",
    uncertaintyNote: "전통적 이른 출애굽 연대에 맞춘 편년이며 가나안 정착의 과정과 고고학적 대응은 학계에서 논쟁적이다.",
    sources: [ESV_BIBLE],
  }),
  historyItem({
    title: "사사 시대",
    start: { year: 1380, era: "BCE", precision: "estimated" },
    end: { year: 1050, era: "BCE", precision: "estimated" },
    tracks: ["israel-history", "christian-history"],
    tags: ["이스라엘사", "성경사", "사사기"],
    summary: "왕정 이전 이스라엘 지파들이 반복되는 배교·압제·구원의 순환을 겪은 것으로 묘사되는 시기다.",
    detail: "사사기는 중앙 왕권이 없던 시기의 지역 지도자들과 신앙적 위기를 기록한다. 복음주의 성경신학에서는 인간의 불순종과 하나님의 반복되는 구원을 보여주는 시기로 읽힌다.",
    confidence: "disputed",
    uncertaintyNote: "사사들의 활동은 일부가 동시대에 서로 다른 지역에서 일어났을 수 있어 단순 합산 편년은 확정적이지 않다.",
    sources: [ESV_BIBLE],
  }),
  historyItem({
    title: "이스라엘 통일왕국",
    start: { year: 1050, era: "BCE", precision: "estimated" },
    end: { year: 930, era: "BCE", precision: "estimated" },
    tracks: ["israel-history", "christian-history", "world-history"],
    tags: ["이스라엘사", "사울", "다윗", "솔로몬", "왕국"],
    summary: "사울·다윗·솔로몬으로 이어지는 왕정이 예루살렘과 성전을 중심으로 통합됐다는 성경의 시기다.",
    detail: "사무엘서와 열왕기는 왕정의 수립, 다윗 언약, 솔로몬 성전 건축을 기록한다. 복음주의 성경신학에서 다윗 왕조는 메시아 약속과 연결되는 중요한 축이다.",
    confidence: "disputed",
    uncertaintyNote: "다윗 왕조의 역사성은 고대 비문으로 일부 뒷받침되지만 통일왕국의 규모와 정확한 연대는 고고학계에서 논쟁적이다.",
    location: location("예루살렘", 31.778, 35.235, "approximate"),
    sources: [ESV_BIBLE],
  }),
  historyItem({
    title: "분열왕국: 이스라엘과 유다",
    start: { year: 930, era: "BCE", precision: "estimated" },
    end: { year: 586, era: "BCE" },
    tracks: ["israel-history", "christian-history", "world-history"],
    tags: ["이스라엘사", "북이스라엘", "유다", "선지자"],
    summary: "솔로몬 이후 왕국이 북이스라엘과 남유다로 나뉘고 선지자들의 사역과 제국의 압력이 이어졌다.",
    detail: "열왕기와 역대기는 분열왕국의 왕들과 언약 신앙의 성쇠를 기록한다. 북왕국은 기원전 722년 아시리아에, 남유다는 기원전 586년 바빌로니아에 멸망했다.",
    confidence: "medium",
    uncertaintyNote: "후기 왕국들의 큰 틀은 비문과 제국 기록으로 확인되지만 초기 분열 시점의 세부 편년에는 차이가 있다.",
    sources: [ESV_BIBLE],
  }),
  historyItem({
    title: "사마리아 함락과 북이스라엘 멸망",
    start: { year: 722, era: "BCE" },
    tracks: ["israel-history", "world-history"],
    tags: ["이스라엘사", "아시리아", "사마리아"],
    summary: "아시리아가 사마리아를 함락하고 북이스라엘 왕국을 제국의 지배 아래 편입했다.",
    detail: "북왕국의 멸망은 열왕기 기록과 아시리아 제국 자료가 만나는 주요 사건이다. 주민 이주와 재편은 이후 사마리아 지역의 역사에도 장기적 영향을 주었다.",
    location: location("고대 사마리아", 32.2763, 35.1897, "approximate"),
    sources: [ESV_BIBLE],
  }),
  historyItem({
    title: "예루살렘 함락과 바빌론 포로기",
    start: { year: 586, era: "BCE" },
    end: { year: 539, era: "BCE" },
    tracks: ["israel-history", "christian-history", "world-history"],
    tags: ["이스라엘사", "바빌론 포로", "예루살렘"],
    summary: "바빌로니아가 예루살렘과 첫 성전을 파괴하고 유다 공동체의 일부를 포로로 이주시켰다.",
    detail: "포로기는 유다 왕국의 종말이자 성전·땅·왕권을 잃은 공동체가 언약과 정체성을 재해석한 시기였다. 예언서와 포로기 전승의 중요한 역사적 배경이 된다.",
    location: location("예루살렘", 31.778, 35.235, "approximate"),
    sources: [ESV_BIBLE],
  }),
  historyItem({
    title: "귀환과 제2성전 재건",
    start: { year: 538, era: "BCE" },
    end: { year: 516, era: "BCE" },
    tracks: ["israel-history", "christian-history", "world-history"],
    tags: ["이스라엘사", "페르시아", "제2성전", "귀환"],
    summary: "페르시아 통치 아래 포로 공동체의 귀환이 시작되고 예루살렘 제2성전이 재건됐다.",
    detail: "고레스의 정책 아래 유다 공동체 일부가 귀환했고 성전이 다시 세워졌다. 에스라·느헤미야 전승은 율법과 공동체 정체성의 재정비를 보여준다.",
    location: location("예루살렘 성전산", 31.778, 35.235, "approximate"),
    sources: [ESV_BIBLE],
  }),
  historyItem({
    title: "마카비 혁명",
    start: { year: 167, era: "BCE" },
    end: { year: 160, era: "BCE" },
    tracks: ["israel-history", "world-history"],
    tags: ["이스라엘사", "마카비", "헬레니즘", "제2성전기"],
    summary: "셀레우코스의 종교 억압에 맞선 유대 반란이 성전 정화와 하스몬 왕조의 기반으로 이어졌다.",
    detail: "마카비 혁명은 헬레니즘 제국 아래 유대교 정체성과 성전 예배를 둘러싼 충돌이었다. 이 시기는 신약 시대 유대 사회의 정치·종교적 배경을 형성했다.",
    location: location("예루살렘", 31.778, 35.235, "approximate"),
    sources: [ESV_BIBLE],
  }),
  historyItem({
    title: "로마의 유대 통치",
    start: { year: 63, era: "BCE" },
    end: { year: 135, era: "CE" },
    tracks: ["israel-history", "world-history", "christian-history"],
    tags: ["이스라엘사", "로마", "유대", "제2성전기"],
    summary: "폼페이우스의 예루살렘 진입 이후 유대가 로마 질서에 편입되고 두 차례 대규모 반란을 겪었다.",
    detail: "헤롯 왕조와 로마 총독 통치는 예수와 초대교회의 직접적인 정치 배경이다. 기원후 70년 성전 파괴와 132~135년 바르 코크바 반란은 유대 사회를 크게 재편했다.",
    location: location("예루살렘", 31.778, 35.235, "approximate"),
    sources: [ROME_EMPIRE, ESV_NEW_TESTAMENT],
  }),
  historyItem({
    title: "예수 그리스도의 생애",
    type: "person",
    start: { year: 4, era: "BCE", precision: "estimated" },
    end: { year: 33, era: "CE", precision: "estimated" },
    basis: "lifespan",
    tracks: ["israel-history", "christian-history", "world-history"],
    tags: ["이스라엘사", "기독교사", "예수", "복음서"],
    summary: "예수의 성육신, 하나님 나라 선포, 십자가와 부활은 개신교 성경 이해에서 구속사의 중심을 이룬다.",
    detail: "복음주의 개신교는 예수 그리스도를 참 하나님이자 참 인간, 구약 약속의 성취로 고백한다. 그의 공생애는 갈릴리와 유대를 중심으로 진행됐고 십자가 죽음과 부활이 복음의 핵심 사건이 된다.",
    confidence: "disputed",
    uncertaintyNote: "탄생은 통상 기원전 6~4년, 십자가는 기원후 30년 또는 33년으로 제시된다. 여기서는 복음주의권에서 널리 쓰이는 기원전 4년~기원후 33년 범위를 사용한다.",
    location: location("예루살렘", 31.778, 35.235, "approximate"),
    sources: [ESV_NEW_TESTAMENT],
  }),
  historyItem({
    title: "예수 그리스도의 십자가와 부활",
    start: { year: 33, precision: "estimated" },
    tracks: ["israel-history", "christian-history", "world-history"],
    tags: ["기독교사", "예수", "십자가", "부활", "복음"],
    summary: "예수의 십자가 죽음과 부활은 복음주의 개신교가 역사와 구원의 결정적 전환점으로 고백하는 사건이다.",
    detail: "복음서에 따르면 예수는 본디오 빌라도 아래 십자가에 달려 죽고 장사된 뒤 제삼일에 부활하셨다. 개신교 신앙은 이 사건을 죄인을 위한 대속과 죽음에 대한 승리의 중심으로 고백한다.",
    confidence: "medium",
    uncertaintyNote: "십자가 처형은 고대 자료로 널리 인정되지만 연도는 30년과 33년 견해가 있다. 부활은 개신교의 핵심 역사적 신앙 고백이며 일반 역사학의 방법론만으로 판정하기 어렵다.",
    location: location("예루살렘", 31.778, 35.235, "approximate"),
    sources: [ESV_NEW_TESTAMENT],
  }),
  historyItem({
    title: "사도 시대와 초대교회의 확장",
    start: { year: 33, precision: "estimated" },
    end: { year: 100, precision: "estimated" },
    tracks: ["israel-history", "christian-history", "world-history"],
    tags: ["기독교사", "사도행전", "오순절", "선교"],
    summary: "오순절 성령 강림 이후 복음이 예루살렘에서 유대·사마리아와 로마 세계로 확산됐다.",
    detail: "사도행전은 교회가 성령의 능력으로 예수 그리스도의 죽음과 부활을 증언하며 확장되는 과정을 기록한다. 바울의 선교와 이방인의 교회 편입은 중요한 전환점이었다.",
    confidence: "medium",
    uncertaintyNote: "시작 연도는 십자가 연대에 따라 30년 또는 33년으로 달라질 수 있으며 종료는 사도 시대의 관례적 범위다.",
    sources: [ESV_ACTS],
  }),
  historyItem({
    title: "이스라엘 국가 수립",
    start: { year: 1948 },
    tracks: ["israel-history", "world-history"],
    tags: ["이스라엘사", "현대 이스라엘", "중동"],
    summary: "영국 위임통치 종료와 함께 이스라엘이 독립을 선언하고 곧바로 주변국과 전쟁에 들어갔다.",
    detail: "1948년 국가 수립은 유대 민족국가의 형성과 팔레스타인 난민 문제, 중동 전쟁의 장기적 출발점이 되었다. 성경 예언과의 관계에 대해서는 개신교 내부에도 서로 다른 해석이 있다.",
    confidence: "high",
    location: location("텔아비브", 32.0853, 34.7818, "approximate"),
    sources: [
      source(
        "reference",
        "History of Israel",
        "Encyclopaedia Britannica",
        "https://www.britannica.com/place/Israel/History",
      ),
    ],
  }),

  historyItem({
    title: "로마 공화정",
    start: { year: 509, era: "BCE" },
    end: { year: 27, era: "BCE" },
    tracks: ["world-history", "philosophy-history"],
    tags: ["로마사", "공화정", "지중해"],
    summary: "로마가 왕정을 대신한 공화정 체제를 발전시키고 이탈리아와 지중해의 패권국으로 성장했다.",
    detail: "집정관, 원로원, 민회가 권력을 나누는 공화정은 신분투쟁과 영토 팽창 속에서 변화했다. 후기에는 대규모 정복, 사회 불평등과 내전이 체제를 흔들었다.",
    location: location("로마", 41.8933, 12.4829, "approximate"),
    sources: [ROME_REPUBLIC],
  }),
  historyItem({
    title: "포에니 전쟁",
    start: { year: 264, era: "BCE" },
    end: { year: 146, era: "BCE" },
    tracks: ["world-history"],
    tags: ["로마사", "카르타고", "포에니 전쟁"],
    summary: "로마와 카르타고의 세 차례 전쟁이 로마의 서부 지중해 패권을 확정했다.",
    detail: "시칠리아를 둘러싼 첫 전쟁, 한니발의 이탈리아 침공, 카르타고 파괴로 이어진 세 전쟁은 로마를 지중해 제국으로 바꾸었다.",
    sources: [ROME_REPUBLIC],
  }),
  historyItem({
    title: "로마 제국 시대",
    start: { year: 27, era: "BCE" },
    end: { year: 476, era: "CE" },
    tracks: ["world-history", "christian-history", "israel-history"],
    tags: ["로마사", "로마 제국", "고대 후기"],
    summary: "아우구스투스의 원수정에서 서로마 황제 폐위까지 로마의 제국 통치가 지중해 세계를 지배했다.",
    detail: "로마 제국은 법, 도시, 도로와 교역망을 광범위하게 통합했다. 예수와 초기 기독교의 역사적 무대였으며, 4세기 기독교 공인과 제국 분할을 거쳐 서방 제국은 476년에 끝났다.",
    confidence: "medium",
    uncertaintyNote: "동로마 제국은 1453년까지 존속했으므로 476년은 서유럽 중심의 관례적 구분이다.",
    sources: [ROME_EMPIRE],
  }),
  historyItem({
    title: "서로마 제국의 종말",
    start: { year: 476 },
    tracks: ["world-history", "christian-history"],
    tags: ["로마사", "서로마", "고대 후기"],
    summary: "오도아케르가 로물루스 아우구스툴루스를 폐위해 서로마 황제권의 관례적 종말을 이루었다.",
    detail: "476년은 서유럽에서 로마 황제권이 사라진 상징적 기준점이다. 정치·사회·문화의 변화는 훨씬 장기적으로 진행됐고 동로마 제국은 계속 존속했다.",
    location: location("라벤나", 44.4184, 12.2035, "approximate"),
    sources: [ROME_EMPIRE],
  }),

  historyItem({
    title: "소크라테스의 생애",
    type: "person",
    start: { year: 470, era: "BCE", precision: "estimated" },
    end: { year: 399, era: "BCE" },
    basis: "lifespan",
    tracks: ["philosophy-history", "world-history"],
    tags: ["철학사", "소크라테스", "고대 그리스"],
    summary: "소크라테스가 대화와 반문을 통해 덕, 지식, 좋은 삶의 문제를 철학의 중심에 놓았다.",
    detail: "저술을 남기지 않은 소크라테스는 플라톤과 크세노폰 등의 기록을 통해 알려진다. 그의 재판과 죽음은 철학적 탐구와 시민 공동체의 긴장을 상징한다.",
    confidence: "medium",
    uncertaintyNote: "생애와 사상의 세부는 서로 다른 후대 증언을 통해 재구성된다.",
    location: location("아테네", 37.9838, 23.7275, "approximate"),
    sources: [sep("Socrates", "socrates")],
  }),
  historyItem({
    title: "플라톤의 생애와 아카데메이아",
    type: "person",
    start: { year: 427, era: "BCE", precision: "estimated" },
    end: { year: 347, era: "BCE", precision: "estimated" },
    basis: "lifespan",
    tracks: ["philosophy-history", "world-history"],
    tags: ["철학사", "플라톤", "아카데메이아"],
    summary: "플라톤이 대화편과 아카데메이아를 통해 형상, 지식, 정의와 국가의 문제를 체계적으로 탐구했다.",
    detail: "플라톤의 철학은 소크라테스의 문제의식을 계승하면서 형상론, 영혼론, 정치철학을 전개했다. 그가 세운 아카데메이아는 서양 철학 교육의 대표적 전통이 되었다.",
    confidence: "medium",
    uncertaintyNote: "생몰년과 대화편의 정확한 집필 순서는 추정에 의존한다.",
    location: location("아테네", 37.9838, 23.7275, "approximate"),
    sources: [sep("Plato", "plato")],
  }),
  historyItem({
    title: "아리스토텔레스의 생애",
    type: "person",
    start: { year: 384, era: "BCE" },
    end: { year: 322, era: "BCE" },
    basis: "lifespan",
    tracks: ["philosophy-history", "science-history", "world-history"],
    tags: ["철학사", "과학사", "아리스토텔레스"],
    summary: "아리스토텔레스가 논리학, 형이상학, 윤리학, 정치학과 자연 연구를 광범위하게 체계화했다.",
    detail: "아리스토텔레스의 저작은 존재와 원인, 덕과 행복, 정치 공동체뿐 아니라 생물과 자연 현상까지 다룬다. 그의 개념 체계는 고대 후기와 중세 학문에 지대한 영향을 주었다.",
    location: location("아테네 리케이온", 37.9755, 23.7483, "approximate"),
    sources: [sep("Aristotle", "aristotle")],
  }),
  historyItem({
    title: "토마스 아퀴나스의 『신학대전』 집필",
    type: "book",
    start: { year: 1265 },
    end: { year: 1274 },
    basis: "publication",
    tracks: ["philosophy-history", "christian-history"],
    tags: ["철학사", "스콜라철학", "토마스 아퀴나스"],
    summary: "아퀴나스가 아리스토텔레스 철학과 기독교 신학을 종합한 『신학대전』을 집필했다.",
    detail: "『신학대전』은 하나님, 창조, 인간 행위, 덕, 법, 그리스도와 성례를 논증 형식으로 다룬 중세 스콜라철학의 대표 저작이다. 종교개혁 전통은 여러 교리를 비판하면서도 그의 철학적 영향과 논증을 계속 연구해 왔다.",
    sources: [sep("Saint Thomas Aquinas", "aquinas")],
  }),
  historyItem({
    title: "데카르트의 『성찰』 출간",
    type: "book",
    start: { year: 1641 },
    basis: "publication",
    tracks: ["philosophy-history", "science-history"],
    tags: ["철학사", "데카르트", "근대철학", "합리론"],
    summary: "데카르트가 방법적 회의와 코기토를 통해 지식의 확실한 토대를 새롭게 세우려 했다.",
    detail: "『제일철학에 관한 성찰』은 감각과 전통적 권위를 의심하고 생각하는 주체의 확실성에서 출발한다. 정신과 물체의 구분은 근대 인식론과 심신 문제의 핵심 의제가 되었다.",
    sources: [sep("Rene Descartes", "descartes")],
  }),
  historyItem({
    title: "칸트의 『순수이성비판』 출간",
    type: "book",
    start: { year: 1781 },
    basis: "publication",
    tracks: ["philosophy-history"],
    tags: ["철학사", "칸트", "비판철학"],
    summary: "칸트가 경험의 가능 조건과 이성의 한계를 분석해 합리론과 경험론의 대립을 새롭게 구성했다.",
    detail: "『순수이성비판』은 인간 인식이 대상을 수동적으로 복사하는 것이 아니라 감성과 오성의 형식을 통해 경험을 구성한다고 논증한다. 근대철학과 이후 독일 관념론의 분기점이 되었다.",
    sources: [sep("Immanuel Kant", "kant")],
  }),
  historyItem({
    title: "롤스의 『정의론』 출간",
    type: "book",
    start: { year: 1971 },
    basis: "publication",
    tracks: ["philosophy-history", "american-history"],
    tags: ["철학사", "정치철학", "존 롤스", "정의론"],
    summary: "롤스가 원초적 입장과 무지의 베일을 통해 공정으로서의 정의 원리를 제시했다.",
    detail: "『정의론』은 자유롭고 평등한 시민들이 공정한 조건에서 선택할 사회 기본구조의 원리를 탐구했다. 20세기 후반 영미 정치철학의 논의를 크게 재활성화했다.",
    sources: [sep("John Rawls", "rawls")],
  }),

  historyItem({
    title: "유클리드의 『원론』",
    type: "book",
    start: { year: 300, era: "BCE", precision: "estimated" },
    basis: "publication",
    tracks: ["science-history", "philosophy-history", "world-history"],
    tags: ["과학사", "수학사", "유클리드", "기하학"],
    summary: "유클리드가 공리와 증명에 기초해 고대 수학 지식을 체계화한 『원론』을 편찬했다.",
    detail: "『원론』은 정의, 공준, 공리에서 정리를 연역하는 구조를 보여주며 수학적 증명의 대표 모델이 되었다. 2천 년 넘게 수학교육과 과학적 논증에 영향을 주었다.",
    confidence: "medium",
    uncertaintyNote: "유클리드의 생애와 정확한 편찬 연도는 확실하지 않다.",
    location: location("알렉산드리아", 31.2001, 29.9187, "approximate"),
    sources: [
      source(
        "reference",
        "Euclid",
        "MacTutor History of Mathematics",
        "https://mathshistory.st-andrews.ac.uk/Biographies/Euclid/",
      ),
    ],
  }),
  historyItem({
    title: "이슬람 황금기의 과학과 번역 운동",
    start: { year: 750, precision: "estimated" },
    end: { year: 1258, precision: "estimated" },
    tracks: ["science-history", "philosophy-history", "world-history"],
    tags: ["과학사", "이슬람 황금기", "번역 운동", "바그다드"],
    summary: "아랍어권 학자들이 고대 지식을 번역·비판·확장하며 수학, 의학, 천문학과 광학을 발전시켰다.",
    detail: "바그다드를 비롯한 여러 학문 중심지에서 그리스·페르시아·인도 지식이 아랍어로 번역되었다. 알콰리즈미, 이븐 시나, 이븐 알하이삼 등의 연구는 이후 라틴어권 학문에도 큰 영향을 주었다.",
    confidence: "medium",
    uncertaintyNote: "황금기는 지역과 분야에 따라 시작·종료 시점이 다르며 750~1258년은 대표적 범위다.",
    location: location("바그다드", 33.3152, 44.3661, "approximate"),
    sources: [
      source(
        "reference",
        "Islamic Science and Mathematics",
        "The Metropolitan Museum of Art",
        "https://www.metmuseum.org/essays/science-and-the-art-of-the-islamic-world",
      ),
    ],
  }),
  historyItem({
    title: "코페르니쿠스의 『천구의 회전에 관하여』",
    type: "book",
    start: { year: 1543 },
    basis: "publication",
    tracks: ["science-history", "philosophy-history", "world-history"],
    tags: ["과학사", "코페르니쿠스", "지동설", "과학혁명"],
    summary: "코페르니쿠스가 태양 중심의 행성 체계를 수학적으로 제시해 천문학의 장기적 전환을 촉발했다.",
    detail: "『천구의 회전에 관하여』는 지구의 자전과 공전을 포함한 태양 중심 모형을 제시했다. 즉시 기존 천문학을 대체하지는 않았지만 케플러, 갈릴레이와 뉴턴으로 이어지는 논쟁의 출발점이 되었다.",
    sources: [
      source(
        "reference",
        "Nicolaus Copernicus",
        "MacTutor History of Mathematics",
        "https://mathshistory.st-andrews.ac.uk/Biographies/Copernicus/",
      ),
    ],
  }),
  historyItem({
    title: "뉴턴의 『프린키피아』 출간",
    type: "book",
    start: { year: 1687 },
    basis: "publication",
    tracks: ["science-history", "philosophy-history", "world-history"],
    tags: ["과학사", "뉴턴", "고전역학", "중력"],
    summary: "뉴턴이 운동 법칙과 만유인력을 수학적으로 체계화해 천상과 지상의 운동을 하나의 이론으로 설명했다.",
    detail: "『자연철학의 수학적 원리』는 운동의 세 법칙과 만유인력을 통해 행성 운동과 지상 물체의 운동을 통일했다. 근대 물리학의 대표적 이론 체계를 세웠다.",
    location: location("런던 왕립학회", 51.505, -0.132, "approximate"),
    sources: [
      source(
        "reference",
        "Isaac Newton",
        "MacTutor History of Mathematics",
        "https://mathshistory.st-andrews.ac.uk/Biographies/Newton/",
      ),
    ],
  }),
  historyItem({
    title: "다윈의 『종의 기원』 출간",
    type: "book",
    start: { year: 1859 },
    basis: "publication",
    tracks: ["science-history", "philosophy-history", "world-history"],
    tags: ["과학사", "다윈", "진화", "자연선택"],
    summary: "다윈이 자연선택을 통한 생물 진화 이론과 광범위한 증거를 제시했다.",
    detail: "『종의 기원』은 종이 고정돼 있다는 관점을 비판하고 변이, 생존과 번식의 차이를 통해 종의 변화를 설명했다. 생물학의 통합적 연구 프로그램을 크게 바꾸었다.",
    sources: [
      source(
        "reference",
        "On the Origin of Species",
        "Darwin Correspondence Project, University of Cambridge",
        "https://www.darwinproject.ac.uk/about-darwin/origin-species",
      ),
    ],
  }),
  historyItem({
    title: "아인슈타인의 상대성이론",
    start: { year: 1905 },
    end: { year: 1915 },
    basis: "activity",
    tracks: ["science-history", "philosophy-history", "world-history"],
    tags: ["과학사", "아인슈타인", "특수상대성이론", "일반상대성이론"],
    summary: "특수상대성이론과 일반상대성이론이 시간·공간·중력에 대한 고전적 이해를 근본적으로 바꾸었다.",
    detail: "1905년 특수상대성이론은 빛의 속도와 관성계의 물리를 새롭게 정식화했고, 1915년 일반상대성이론은 중력을 시공간의 곡률로 설명했다.",
    sources: [
      source(
        "reference",
        "Albert Einstein",
        "MacTutor History of Mathematics",
        "https://mathshistory.st-andrews.ac.uk/Biographies/Einstein/",
      ),
    ],
  }),
  historyItem({
    title: "양자역학의 정립",
    start: { year: 1925 },
    end: { year: 1927 },
    tracks: ["science-history", "philosophy-history", "world-history"],
    tags: ["과학사", "양자역학", "하이젠베르크", "슈뢰딩거"],
    summary: "행렬역학과 파동역학, 불확정성 원리가 미시세계의 새로운 물리 이론을 형성했다.",
    detail: "하이젠베르크, 슈뢰딩거, 보른, 보어 등은 고전역학으로 설명되지 않던 원자 현상을 수학적으로 정식화했다. 측정과 확률의 의미는 과학철학의 핵심 논쟁도 낳았다.",
    sources: [
      source(
        "reference",
        "The Quantum Age",
        "Nobel Prize",
        "https://www.nobelprize.org/prizes/themes/the-quantum-age/",
      ),
    ],
  }),
  historyItem({
    title: "DNA 이중나선 구조 규명",
    start: { year: 1953 },
    tracks: ["science-history", "world-history"],
    tags: ["과학사", "DNA", "유전학", "분자생물학"],
    summary: "DNA의 이중나선 구조가 제시돼 유전정보의 저장과 복제 원리를 이해하는 전환점이 마련됐다.",
    detail: "왓슨과 크릭의 모형은 로절린드 프랭클린과 모리스 윌킨스 등의 X선 회절 연구를 포함한 축적된 증거에 의존했다. 이 구조는 현대 분자생물학의 핵심 기반이 되었다.",
    location: location("케임브리지 캐번디시 연구소", 52.208, 0.1218, "approximate"),
    sources: [
      source(
        "reference",
        "Exploring life's smallest details",
        "Nobel Prize",
        "https://www.nobelprize.org/stories/cells-nerves-genes/",
      ),
    ],
  }),
  historyItem({
    title: "아폴로 11호 달 착륙",
    start: { year: 1969 },
    tracks: ["science-history", "american-history", "world-history"],
    tags: ["과학사", "미국사", "우주개발", "아폴로 11"],
    summary: "아폴로 11호 우주비행사들이 인류 최초로 달에 착륙하고 표본을 지구로 가져왔다.",
    detail: "1969년 7월 닐 암스트롱과 버즈 올드린은 달 표면에 착륙했고 마이클 콜린스는 달 궤도를 비행했다. 냉전 우주경쟁의 정점이자 행성과학 연구의 중요한 전환점이었다.",
    location: location("달 고요의 바다", 0.6741, 23.4729, "approximate"),
    sources: [
      source(
        "reference",
        "History of Lunar Exploration",
        "NASA Science",
        "https://science.nasa.gov/moon/exploration/",
      ),
    ],
  }),
  historyItem({
    title: "CRISPR-Cas9 유전자 편집법 발표",
    type: "technology",
    start: { year: 2012 },
    tracks: ["science-history", "world-history"],
    tags: ["과학사", "CRISPR", "유전자 편집", "생명공학"],
    summary: "CRISPR-Cas9을 정밀한 유전자 편집 도구로 활용하는 방법이 발표돼 생명과학 연구를 크게 바꾸었다.",
    detail: "에마뉘엘 샤르팡티에와 제니퍼 다우드나는 세균의 면역 체계를 이용해 원하는 DNA를 절단할 수 있는 방법을 제시했다. 의학적 가능성과 함께 안전·윤리 문제도 중요한 과제가 됐다.",
    sources: [
      source(
        "reference",
        "The Nobel Prize in Chemistry 2020",
        "Nobel Prize",
        "https://www.nobelprize.org/prizes/chemistry/2020/press-release/",
      ),
    ],
  }),
];

function historyItem(input: SeedItem): ImportItem {
  return {
    title: input.title,
    type: input.type ?? "event",
    time: {
      start: instant(input.start),
      end: input.end ? instant(input.end) : null,
      basis:
        input.basis ??
        (input.type === "person" ? "lifespan" : input.end ? "duration" : "point"),
    },
    trackKeys: input.tracks,
    tags: input.tags,
    importance: input.importance ?? "core",
    summary: input.summary,
    detailMarkdown: input.detail,
    recordLevel: "standard",
    confidence: input.confidence ?? "high",
    uncertaintyNote: input.uncertaintyNote ?? null,
    location: input.location ?? null,
    sources: input.sources,
  };
}

function instant(input: DateSpec): ImportItem["time"]["start"] {
  return {
    year: input.year,
    era: input.era ?? "CE",
    precision: input.precision ?? "year",
  };
}

function location(
  name: string,
  latitude: number,
  longitude: number,
  precision: "exact" | "approximate",
): NonNullable<ImportItem["location"]> {
  return { name, latitude, longitude, precision };
}

function source(
  type: ImportItem["sources"][number]["type"],
  title: string,
  author: string,
  url: string,
): ImportItem["sources"][number] {
  return { type, title, author, url };
}

function sep(title: string, slug: string) {
  return source(
    "reference",
    title,
    "Stanford Encyclopedia of Philosophy",
    `https://plato.stanford.edu/entries/${slug}/`,
  );
}
